---
title: "zmPDSwR Chapter 2"
author: "coop711"
date: "2015년 9월 10일"
output: html_document
---

# Data Read In

* Listing 2.1

```{r}
setwd("~/Dropbox/Works/Class/Data_Science/R.WD/zmPDSwR/")
uciCar <- read.table("../../zmPDSwR/UCICar/car.data.csv", sep=",", header=TRUE)
```

* Listing 2.2

```{r}
class(uciCar)
summary(uciCar)
dim(uciCar)
str(uciCar)
head(uciCar)
```

* Listing 2.3

```{r}
d <- read.table(paste('http://archive.ics.uci.edu/ml/',
   'machine-learning-databases/statlog/german/german.data',sep=''),
   stringsAsFactors=F,header=F)
print(d[1:3,])
```

* Listing 2.4

```{r}
colnames(d) <- c('Status.of.existing.checking.account',
   'Duration.in.month',  'Credit.history', 'Purpose',
   'Credit.amount', 'Savings account/bonds',
   'Present.employment.since',
   'Installment.rate.in.percentage.of.disposable.income',
   'Personal.status.and.sex', 'Other.debtors/guarantors',
   'Present.residence.since', 'Property', 'Age.in.years',
   'Other.installment.plans', 'Housing',
   'Number.of.existing.credits.at.this.bank', 'Job',
   'Number.of.people.being.liable.to.provide.maintenance.for',
   'Telephone', 'foreign.worker', 'Good.Loan')
options(width=132)
print(d[1:3,])
```
* Listing 2.5

```{r}
mapping <- list('A11'='... < 0 DM',
 'A12'='0 <= ... < 200 DM',
 'A13'='... >= 200 DM / salary assignments for at least 1 year',
 'A14'='no checking account',
 'A30'='no credits taken/all credits paid back duly',
 'A31'='all credits at this bank paid back duly',
 'A32'='existing credits paid back duly till now',
 'A33'='delay in paying off in the past',
 'A34'='critical account/other credits existing (not at this bank)',
 'A40'='car (new)',
 'A41'='car (used)',
 'A42'='furniture/equipment',
 'A43'='radio/television',
 'A44'='domestic appliances',
 'A45'='repairs',
 'A46'='education',
 'A47'='(vacation - does not exist?)',
 'A48'='retraining',
 'A49'='business',
 'A410'='others',
 'A61'='... < 100 DM',
 'A62'='100 <= ... < 500 DM',
 'A63'='500 <= ... < 1000 DM',
 'A64'='.. >= 1000 DM',
 'A65'='unknown/ no savings account',
 'A71'='unemployed',
 'A72'='... < 1 year',
 'A73'='1 <= ... < 4 years',
 'A74'='4 <= ... < 7 years',
 'A75'='.. >= 7 years',
 'A91'='male : divorced/separated',
 'A92'='female : divorced/separated/married',
 'A93'='male : single',
 'A94'='male : married/widowed',
 'A95'='female : single',
 'A101'='none',
 'A102'='co-applicant',
 'A103'='guarantor',
 'A121'='real estate',
 'A122'='if not A121 : building society savings agreement/life insurance',
 'A123'='if not A121/A122 : car or other, not in attribute 6',
 'A124'='unknown / no property',
 'A141'='bank',
 'A142'='stores',
 'A143'='none',
 'A151'='rent',
 'A152'='own',
 'A153'='for free',
 'A171'='unemployed/ unskilled - non-resident',
 'A172'='unskilled - resident',
 'A173'='skilled employee / official',
 'A174'='management/ self-employed/highly qualified employee/ officer',
 'A191'='none',
 'A192'='yes, registered under the customers name',
 'A201'='yes',
 'A202'='no')
```

* Listing 2.6의 구조를 파악하기 위해서 

```{r}
sapply(d, class)
head(d[, 4])
mapping[head(d[, 4])]
as.character(mapping[head(d[, 4])])
```

* `d`의 복제를 만들어 두고,

```{r}
d.2 <- d
```

* Listing 2.6

```{r}
for(i in 1:dim(d)[2]) {
  if(class(d[, i])=="character") {
    d[, i] <- as.factor(as.character(mapping[d[, i]]))
    }
  }
str(d)
d$Good.Loan <- factor(ifelse(d$Good.Loan == 1, "GoodLoan", "BadLoan"))
str(d)
```

* `for` loop이 보기 싫다면, 

```{r}
(l.char <- sapply(d.2, class) == "character")
names(l.char) <- NULL
l.char
which(l.char)
d.char <- subset(d.2, select = l.char)
str(d.char)
d.factor <- sapply(d.char, function(x) factor(as.character(mapping[x])), simplify=FALSE)
str(d.factor)
d.2[l.char] <- d.factor
str(d.2)
d.2$Good.Loan <- factor(ifelse(d.2$Good.Loan == 1, "GoodLoan", "BadLoan"))
str(d.2)
```

* 몇 가지 자료 검색

```{r}
d[1:3, "Purpose"]
summary(d$Purpose)
```

* Listing 7

```{r}
(tbl <- table("Purpose" = d$Purpose, "Good Loan?" = d$Good.Loan))
(tbl.df <- data.frame(tbl))
options(digits=2)
prop.table(table("Purpose" = d$Purpose, "Good Loan?" = d$Good.Loan), 1)
```

* ggplot

```{r}
library(ggplot2)
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan))
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan)) + coord_flip()
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="dodge")
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="dodge") + coord_flip()
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="fill")
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="fill") + coord_flip()
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="fill") + coord_flip() + ylab("Proportion")
```

* `tbl.df`로 그리면,

```{r}
tbl.df
names(tbl.df)[2] <- c("Status")
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity")
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity") +
  coord_flip()
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity", position="dodge")
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity", position="dodge") +
  coord_flip()
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity", position="fill")
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity", position="fill") +
  coord_flip() 
ggplot(tbl.df, aes(x=Purpose, y=Freq, fill=Status)) + geom_bar(stat="identity", position="fill") +
  coord_flip() +
  xlab("Purpose") + ylab("Proportion")
ggplot(tbl.df, aes(x=reorder(Purpose, Freq), y=Freq, fill=Status)) + geom_bar(stat="identity") +
  coord_flip() +
  xlab("Purpose")
```

* 한글화 

```{r}
theme.kr <- theme(axis.title.x = element_text(family="HCR Batang LVT"),
axis.title.y = element_text(family="HCR Batang LVT"),
axis.text.x = element_text(family="HCR Batang LVT"),
axis.text.y = element_text(family="HCR Batang LVT"),
plot.title = element_text(family="HCR Batang LVT"),
legend.title = element_text(family="HCR Batang LVT"),
legend.text = element_text(family="HCR Batang LVT"))
ggplot(d) + geom_bar(aes(x=Purpose, fill=Good.Loan), position="fill") + coord_flip() +
  theme.kr +
  ylab("비율") + xlab("대출목적") + 
  labs(fill="신용판정") +
  ggtitle("대출 목적과 신용등급") + 
  scale_fill_discrete(labels=c("불량", "양호")) 
ggplot(tbl.df, aes(x=reorder(Purpose, Freq), y=Freq, fill=Status)) + geom_bar(stat="identity") + coord_flip() +
  theme.kr +
  ylab("인원") + xlab("대출목적") + 
  labs(fill="신용판정") +
  ggtitle("대출 목적과 신용등급") + 
  scale_fill_discrete(labels=c("불량", "양호"))
```