---
title: "zmPDSwR Chapter 1"
author: "coop711"
date: "2015년 9월 10일"
output: pdf_document
---

Data
----

```{r}
setwd("~/Dropbox/Works/Class/Data_Science/R.WD/zmPDSwR")
load("~/Dropbox/Works/Class/Data_Science/R.WD/zmPDSwR/GCDData.RData")
ls()
options(width=180)
str(creditdata)
```

* 작업 편의상 `creditdata` 를 등록

```{r}
attach(creditdata)
head(Good.Loan, n=10)
table(Good.Loan)
options(digits=2)
prop.table(table(Good.Loan))
table(Credit.history, Good.Loan)
prop.table(table(Credit.history, Good.Loan), margin=1)
```

```{r}
par(pin=c(4, 4), mai=c(1.0, 4.5, 1.0, 0.5))
CG.percentage <- prop.table(table(Credit.history, Good.Loan), margin=1)
o.GL <- order(CG.percentage[,1])
barplot(t(CG.percentage[o.GL,]),las=1, horiz=TRUE)
title(xlab="Fraction of Defaulted Loans", ylab="")
```

* ggplot 으로 그리면,

```{r}
library(ggplot2)
ggplot(creditdata) + geom_bar(aes(x=Credit.history, fill=Good.Loan), position="fill") + coord_flip()
```

* Listing 1.1

```{r}
library(rpart)
model <- rpart(Good.Loan ~ Duration.in.month +
                 Installment.rate.in.percentage.of.disposable.income +
                 Credit.amount +
                 Other.installment.plans,
               data=d, 
               control=rpart.control(maxdepth=4),
               method="class")
model
```

* Listing 1.2

```{r}
resultframe <- data.frame(Good.Loan=creditdata$Good.Loan,
                          pred=predict(model, type="class"))
rtab <- table(resultframe)
rtab
sum(diag(rtab))/sum(rtab)
sum(rtab[1,1])/sum(rtab[,1])
sum(rtab[1,1])/sum(rtab[1,])
sum(rtab[2,1])/sum(rtab[2,])
```

* Listing 1.3

```{r}
tab1 <- as.table(matrix(data=c(50,6,0,44),nrow=2,ncol=2))
dimnames(tab1) <- list('loan.as.pct.disposable.income'=
      c('LT.15pct','GT.15pct'),
   'loan.quality.pop1'=
      c('goodloan','badloan'))
tab1
tab2 <- as.table(matrix(data=c(34,18,16,32),nrow=2,ncol=2))
dimnames(tab2) <- list('loan.as.pct.disposable.income'=
      c('LT.15pct','GT.15pct'),
   'loan.quality.pop2'=
      c('goodloan','badloan'))
tab2
```

